// <auto-generated />
namespace MovieFanatic.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-beta1-30515")]
    public sealed partial class ConfigureSoftDelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConfigureSoftDelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201406010201040_ConfigureSoftDelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
