// <auto-generated />
namespace MovieFanatic.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CreateMovie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateMovie));
        
        string IMigrationMetadata.Id
        {
            get { return "201405220245167_CreateMovie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
